### ISSUE TITLE
Tech Challenge Fase 04 : 01 Refatore o projeto - Pedido

### ISSUE THREAD

**Issue by RenanSX** [tech-challenge-grupo-6/tech-challenge#144]
Pedido: responsável por retornar as informações necessárias para montar um pedido.

Lembre-se de trabalhar com bancos de dados para cada aplicação. Use ao menos um banco de dados NoSQL e um SQL; caso queira fazer com mais bancos, você pode decidir quais utilizar.

**Comment by VitorSouza23** [comment]
Repo link: https://github.com/tech-challenge-grupo-6/tech-challenge-order
